"""tickets

Revision ID: 6c1c5dd0fd5a
Revises: ed57404bf2ae
Create Date: 2021-02-09 14:54:04.874507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c1c5dd0fd5a'
down_revision = 'ed57404bf2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_flights',
    sa.Column('ticket_no', sa.String(length=13), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('fare_conditions', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False)
    )
    op.create_table('tickets',
    sa.Column('ticket_no', sa.String(length=13), nullable=False),
    sa.Column('book_ref', sa.String(length=6), nullable=False),
    sa.Column('passenger_id', sa.String(length=20), nullable=False),
    sa.Column('passenger_name', sa.Text(), nullable=False),
    sa.Column('contact_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('ticket_no')
    )
    op.create_index(op.f('ix_tickets_passenger_id'), 'tickets', ['passenger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_passenger_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('ticket_flights')
    # ### end Alembic commands ###
