"""flights

Revision ID: ed57404bf2ae
Revises: 1099e5caf5f0
Create Date: 2021-02-09 10:00:23.772152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed57404bf2ae'
down_revision = '1099e5caf5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_no', sa.String(length=6), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departure_airport', sa.String(length=3), nullable=False),
    sa.Column('arrival_airport', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aircraft_code', sa.String(length=3), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Coled57404bf2aeumn('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arrival_airport'], ['airports.airport_code'], ),
    sa.ForeignKeyConstraint(['departure_airport'], ['airports.airport_code'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###
