"""post

Revision ID: 442f93b81d4a
Revises: ba4c10cd1c2e
Create Date: 2021-02-14 17:51:05.766036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442f93b81d4a'
down_revision = 'ba4c10cd1c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
