"""create_table_message

Revision ID: 6356fd90ab82
Revises: 
Create Date: 2021-01-26 08:35:52.737151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6356fd90ab82"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("polarity", sa.Float(), nullable=False),
        sa.Column("subjectivity", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    # ### end Alembic commands ###
